openapi: '3.0.0'
info:
  version: '1.0'
  title: zaP! 🫠 API Documentation

servers:
  - url: /api

tags:
  - name: Triggers
    description: Endpoints to manage triggers
  - name: Oracles
    description: Endpoints to manage oracles
  - name: Rollup
    description: Endpoints to manage Cartesi RISC-V

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      $ref: '../users/user.yaml#/User'
  responses:
    $ref: './errors.yaml'

security:
  - BearerAuth: []

paths:
  $ref: './paths.yaml'
