openapi: '3.0.0'
info:
  version: '1.0'
  title: Start-UI API Contract
tags:
  - name: Account
    description: Endpoints to manage account
  - name: Users
    description: Endpoints to manage users
paths:
  $ref: './paths.yaml'
components:
  schemas:
    User:
      $ref: '../users/user.yaml#/User'
    UserDTO:
      $ref: '../users/user.yaml#/UserDTO'
    ErrorResponse:
      $ref: './errors.yaml#/ErrorResponse'
  responses:
    $ref: './errors.yaml'
